// <auto-generated />
using Katameros;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Katameros.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Katameros.Models.AnnualReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("C_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day_Tune")
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Month_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month_Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Other")
                        .HasColumnType("TEXT");

                    b.Property<string>("P_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("X_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AnnualReadings");
                });

            modelBuilder.Entity("Katameros.Models.Bible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bibles");
                });

            modelBuilder.Entity("Katameros.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Katameros.Models.BooksTranslation", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookId", "LanguageId");

                    b.ToTable("BooksTranslations");
                });

            modelBuilder.Entity("Katameros.Models.Feast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Feasts");
                });

            modelBuilder.Entity("Katameros.Models.FeastsTranslation", b =>
                {
                    b.Property<int>("FeastId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FeastId", "LanguageId");

                    b.ToTable("FeastsTranslations");
                });

            modelBuilder.Entity("Katameros.Models.GreatLentReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("C_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("L_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prophecy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seasonal_Tune")
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Gospel_Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Psalm_Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("Weather_Prayers")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<string>("X_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GreatLentReadings");
                });

            modelBuilder.Entity("Katameros.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Katameros.Models.PentecostReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("C_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("L_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Gospel_Ref")
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Psalm_Ref")
                        .HasColumnType("TEXT");

                    b.Property<int>("Week")
                        .HasColumnType("INTEGER");

                    b.Property<string>("X_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PentecostReadings");
                });

            modelBuilder.Entity("Katameros.Models.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("Katameros.Models.ReadingsMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReadingsMetadatas");
                });

            modelBuilder.Entity("Katameros.Models.ReadingsMetadatasTranslation", b =>
                {
                    b.Property<int>("ReadingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReadingsMetadatasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ReadingId", "ReadingsMetadatasId", "LanguageId");

                    b.ToTable("ReadingsMetadatasTranslations");
                });

            modelBuilder.Entity("Katameros.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Katameros.Models.SectionsMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SectionsMetadatas");
                });

            modelBuilder.Entity("Katameros.Models.SectionsMetadatasTranslation", b =>
                {
                    b.Property<int>("SectionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionsMetadatasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SectionsId", "SectionsMetadatasId", "LanguageId");

                    b.ToTable("SectionsMetadatasTranslations");
                });

            modelBuilder.Entity("Katameros.Models.Sentences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sentences");
                });

            modelBuilder.Entity("Katameros.Models.SentencesTranslation", b =>
                {
                    b.Property<int>("SentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SentenceId", "LanguageId");

                    b.ToTable("SentencesTranslations");
                });

            modelBuilder.Entity("Katameros.Models.SubSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubSections");
                });

            modelBuilder.Entity("Katameros.Models.SubSectionsMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubSectionsMetadatas");
                });

            modelBuilder.Entity("Katameros.Models.SubSectionsMetadatasTranslation", b =>
                {
                    b.Property<int>("SubSectionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubSectionsMetadatasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubSectionsId", "SubSectionsMetadatasId", "LanguageId");

                    b.ToTable("SubSectionsMetadatasTranslations");
                });

            modelBuilder.Entity("Katameros.Models.SundayReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("C_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Day_Tune")
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Month_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month_Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Other")
                        .HasColumnType("TEXT");

                    b.Property<string>("P_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("V_Psalm_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("X_Gospel_Ref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SundayReadings");
                });

            modelBuilder.Entity("Katameros.Models.Synaxarium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Synaxarium");
                });

            modelBuilder.Entity("Katameros.Models.Verse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BibleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
