CREATE TABLE [dbo].[AnnualReadings] (
    [Id]           INT           IDENTITY (1, 1) NOT NULL,
    [Month_Number] INT           NOT NULL,
    [Month_Name]   VARCHAR (300) NOT NULL,
    [Day]          INT           NOT NULL,
    [Other]        VARCHAR (300) CONSTRAINT [DF__AnnualRea__Other__282DF8C2] DEFAULT (NULL) NULL,
    [Day_Tune]     VARCHAR (300) CONSTRAINT [DF__AnnualRea__Day_T__29221CFB] DEFAULT (NULL) NULL,
    [DayName]      VARCHAR (300) CONSTRAINT [DF__AnnualRea__DayNa__2A164134] DEFAULT (NULL) NULL,
    [Season]       VARCHAR (300) CONSTRAINT [DF__AnnualRea__Seaso__2B0A656D] DEFAULT (NULL) NULL,
    [V_Psalm_Ref]  VARCHAR (300) CONSTRAINT [DF__AnnualRea__V_Psa__2BFE89A6] DEFAULT (NULL) NOT NULL,
    [V_Gospel_Ref] VARCHAR (300) CONSTRAINT [DF__AnnualRea__V_Gos__2CF2ADDF] DEFAULT (NULL) NOT NULL,
    [M_Psalm_Ref]  VARCHAR (300) CONSTRAINT [DF__AnnualRea__M_Psa__2DE6D218] DEFAULT (NULL) NOT NULL,
    [M_Gospel_Ref] VARCHAR (300) CONSTRAINT [DF__AnnualRea__M_Gos__2EDAF651] DEFAULT (NULL) NOT NULL,
    [P_Gospel_Ref] VARCHAR (300) CONSTRAINT [DF__AnnualRea__P_Gos__2FCF1A8A] DEFAULT (NULL) NOT NULL,
    [C_Gospel_Ref] VARCHAR (300) CONSTRAINT [DF__AnnualRea__C_Gos__30C33EC3] DEFAULT (NULL) NOT NULL,
    [X_Gospel_Ref] VARCHAR (300) CONSTRAINT [DF__AnnualRea__X_Gos__31B762FC] DEFAULT (NULL) NOT NULL,
    [L_Psalm_Ref]  VARCHAR (300) CONSTRAINT [DF__AnnualRea__L_Psa__32AB8735] DEFAULT (NULL) NOT NULL,
    [L_Gospel_Ref] VARCHAR (300) CONSTRAINT [DF__AnnualRea__L_Gos__339FAB6E] DEFAULT (NULL) NOT NULL,
    CONSTRAINT [PK__AnnualRe__3214EC079764EBBC] PRIMARY KEY CLUSTERED ([Id] ASC)
);



